### ISSUE TITLE
'pnpm dev' breake down

### ISSUE THREAD

**Issue by pmieten** [sfxcode/vite-primevue-starter#21]
After run the application with 'pnpm dev'  it stops working after 1-10 minutes with the below error:
`
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($shade, 100) or calc($shade / 100)

More info and automated migrator: https://sass-lang.com/d/slash-div
More info and automated migrator: https://sass-lang.com/d/slash-div

Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\git\vite-primevue-starter\node_modules\.pnpm\vite@2.7.2_sass@1.45.0\node_modules\vite\dist\node\chunks\dep-7817f5b4.js:49184:10)
    at ReaddirpStream.NodeFsHandler$1._boundHandleError (C:\git\vite-primevue-starter\node_modules\.pnpm\vite@2.7.2_sass@1.45.0\node_modules\vite\dist\node\chunks\dep-7817f5b4.js:47670:43)
    at ReaddirpStream.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\DumpStack.log.tmp'
}
 ELIFECYCLE  Command failed with exit code 1.`
![image](https://user-images.githubusercontent.com/17614746/146072790-41864ded-27cf-496a-8705-d998f6bac652.png)

Environment:
OS: Windows 11
Node: v16.13.0
pnpm: 6.23.6

**Comment by sfxcode** [comment]
Hello,

Deprecation warning is fixed with new primeflex version,
but i can not reproduce your error.
Sounds like a Windows Vite Problem, it does not happen on my Mac.

Maybe you can try the latest version.

Good Luck,

Tom

**Comment by pmieten** [comment]
@sfxcode  checkout it:
https://github.com/vitejs/vite/issues/6149
